### ISSUE TITLE
[Bug] Ratings No Longer Working

### ISSUE THREAD

**Issue by EthanHNguyen** [quinton22/VandyScheduler#1]
Hi Quinton!

Great work on VandyScheduler. My friends and I love your extension!

There is an issue fetching the ratings of each professor. Here's a screenshot from open enrollment.
![Screen Shot 2021-07-21 at 8 32 41 AM](https://user-images.githubusercontent.com/23198915/126497175-6fa091f1-c50d-4634-b76e-15ad7c87e000.png)

Each rating shows N/A but there are reviews on the RateMyProfessor website for Professor Piot and Professor Wiltulski.

Thanks for your work!

**Comment by david-a-perez** [comment]
Hi Ethan!
Ran into the same issue here. Created a pull request to fix it. Unsure if @quinton22 will have a chance to merge and update the software. If not, you can always load my fork unpacked with developer mode.
Many thanks to @quinton22  for making this amazing extension!

**Comment by quinton22** [comment]
Thank you for the contribution! I will merge fix and push to Chrome Web Store.
