### ISSUE TITLE
Persistent data for querying professorIds for a given professor

### ISSUE THREAD

**Issue by DavidHuang2002** [quinton22/VandyScheduler#13]
On RMP (rate my prof) website, the URL to a professor's page is: https://www.ratemyprofessors.com/professor/[professorId]. Example: https://www.ratemyprofessors.com/professor/2800298. So mostly, all we need to know is the professor's id for the extension to work.
Our current way of getting a professor's id is that we send a search request to RMP -> get the prof id of the first result, and every time they change their search functionality(which they frequently do) we have to adapt.
Since a professor's id is fixed and the professors at a school don't change much, I think we can have some persistence layer storing the mapping of profName to profId. This can literally just be a .csv file that comes with the extension. This will allow the extension to work for most prof even when RMP's search functionality is done or has changed.

Email me at david.j.huang@vanderbilt.edu if this sounds like something you like to work on! I can tell you more details. We would love your help

**Comment by DavidHuang2002** [comment]
Steps to this feature
- Create a list of all professors in the school
- Scrape RMP to get the id for all professors. Store them in a .csv file. The file should contain (prof name, id)
- Incorporate the CSV file into our extension. The look-up for professor will be -> check .csv file first, if not found -> go to RMP site.

We should update this CSV file every semester

**Comment by quinton22** [comment]
Closing this because the implementation of the graphQL api, but it may be useful to have a backup that parses HTML in the future.
